site_name: Ola
site_url: "https://olamyy.github.io"
site_description: "Ola Wahab's personal website."
repo_url: https://github.com/olamyy/olamyy.github.io
repo_name: olamyy/olamyy.github.io
edit_uri: edit/master/docs/
copyright: "&copy; 2026, Ola Wahab"

theme:
  name: material
  custom_dir: overrides

  font:
    text: Inter
    code: Noto Sans Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - toc.follow
    - navigation.top

  palette:
    - media: "(prefers-color-scheme: light)"

      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/circle-half-full
        name: Switch to light mode

plugins:
  - search
  - privacy
  - blog:
      blog_dir: .
      post_url_date_format: yyyy
      post_url_format: "posts/{file}"
      pagination_per_page: 5

markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra:
  generator: false
  subtitle: "I know I was going somewhere with this, I just seem to have followed the sentence into a blind alley."
  avatar: assets/stewie.jpg
  socials:
    - url: https://x.com/__olamilekan__
      icon: fontawesome/brands/x-twitter
      name: Twitter
    - url: https://www.linkedin.com/in/olamilekan-wahab/
      icon: fontawesome/brands/linkedin
      name: LinkedIn
    - url: https://substack.com/@olamilekan
      icon: simple/substack
      name: Substack

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
